### ISSUE TITLE
Missing image files and missing fonts

### ISSUE THREAD

**Issue by wzmumu** [isteinbrecher/latex2ai#110]
In "Known issues->Missing images files", it is said LaTeX2AI automatically restores the missing items. It is only restored when the link file is saved, but the fonts are missing and the formula does not look the same as it was typed in. Can this be solved by keeping track of the labels in "links" subfolder?

**Comment by isteinbrecher** [comment]
@wzmumu what is the status on this issue? Can it be closed?
