### ISSUE TITLE
Add availability of "Expand"

### ISSUE THREAD

**Issue by HuangXiaoKai** [isteinbrecher/latex2ai#112]
Thank you for your work that makes inserting LaTeX formula in AI so convenient and elegant!

In some cases, it may be good for user to expand the rendered formula into "vector shapes" so the .ai file will be good to go even without this plugin. Or, in rare cases, figure maker may want to bend the simple formula to fit the data curve, which also require the "Expand" function. 

Do you think "Expand" availability necessary and technically achievable?

**Comment by isteinbrecher** [comment]
Thank you for your suggestion. The topic of _embedding_ LaTeX2AI labels into Illustrator is a little bit tricky. However it should already be possible to to what you are suggesting.


> the .ai file will be good to go even without this plugin

If you want to use a `.ai` document with LaTeX2AI labels without the PlugIn, you have to make sure, the `links` folder containing the `pdf` labels stays next to your Illustrator document.


> Or, in rare cases, figure maker may want to bend the simple formula to fit the data curve, which also require the "Expand" function.

For this case two solutions come to my mind:
1. _Bend_ the label directly in LaTeX (e.g., with TikZ)
1. Manually _embedding_ the label in Illustrator, either with the `embed` function (this can lead to issues if the correct fonts are not available on your system) or use the `Object / Flatten Transparency` function and select `Convert All Text to Outlines`. It his is done however, the item will not be editable any more.

**Comment by HuangXiaoKai** [comment]
Yes, thank you. I think `object->Flatten Transparency` is just what I need.
