### ISSUE TITLE
"LaTeX2AI_item.pdf" is created but the plugin tries to open "LaTeX2AI_item_1.pdf"

### ISSUE THREAD

**Issue by raulazo-m** [isteinbrecher/latex2ai#115]
Hello, the plugin creates the pdf with the equation in the corresponding folder:

![image](https://user-images.githubusercontent.com/85465886/200042043-f6cb6d2d-6672-439d-a61f-dad8d153b748.png)

But then it tries to open a file that does not exist "LaTeX2AI_item_1.pdf"

![image](https://user-images.githubusercontent.com/85465886/200042169-8517ac79-dbd4-4991-9fad-3db982186c96.png)

Thanks for your help!

**Comment by isteinbrecher** [comment]
LaTeX2AI generates all item generates all labels in a single pdf file `LaTeX2AI_item.pdf` (each label is a page in this document, in your case probably just 1) and then splits it into individual pdf files using ghostscript. It seems like the split command did not work in your case. What version of ghostscript do you have on your system?

**Comment by raulazo-m** [comment]
I was using a version that I had installed before and that came with TexLive. But now that you mention about the version I installed the most updated one and the plugin is already working.

Thank you very much!
