### ISSUE TITLE
Toolmousedown error caught  and notify error  caught.

### ISSUE THREAD

**Issue by wzmumu** [isteinbrecher/latex2ai#116]
hello,
when i want to insert an equation, there comes an "Toolmousedown error caught " with message
![W ZE2H2GD{0(_1E$%SQR$K6](https://user-images.githubusercontent.com/105213233/220940913-a0e56eb4-71ae-4fc8-8388-97576368ece0.jpg)

and when i modify an exsiting equation, there comes "notify error  caught"
![W ZE2H2GD{0(_1E$%SQR$K6](https://user-images.githubusercontent.com/105213233/220942398-053db755-7b49-42f9-94ee-a2aaee28f246.jpg)

**Comment by isteinbrecher** [comment]
My first guess is, that there is an issue with postscript. Can you post your postscript version and the LaTeX code that you try to compile?

**Comment by wzmumu** [comment]
Any latex can lead to error actually. I do not know what you need. I upload gswin32.
[gswin32c.zip](https://github.com/isteinbrecher/latex2ai/files/10831958/gswin32c.zip)

**Comment by isteinbrecher** [comment]
Can you post your full ghostscript path (it is listed in the options panel, ![options](https://raw.githubusercontent.com/isteinbrecher/latex2ai/main/l2a/resources/options_light.png?raw=true "LaTeX2AI options")). Also can you go to the folder mentioned in the error message (`c:\Users\wzmumu\AppData\Local\Temp\LaTeX2AI\`) and post the contents?
There should be the following PDF file `LaTeX2AI_item.pdf` which contains the compiled LaTeX code - ist this the case?

**Comment by wzmumu** [comment]
The full path of gswin is C:\Program Files\texlive\2021\tlpkg\tlgs\bin
The full path of ps viewer is "C:\Program Files\texlive\2021\bin\win32\psviewer.exe" "?am.ps"
dvi "C:\Program Files\texlive\2021\bin\win32\dviout.exe" "?am.dvi"
I snap the option of my texstudio
![图片](https://user-images.githubusercontent.com/105213233/222062909-a24b1ebc-ef08-4495-aecf-26faf869abc7.png)

Log is here.

[LaTeX2AI_item.log](https://github.com/isteinbrecher/latex2ai/files/10857812/LaTeX2AI_item.log)

In fact, the LaTeX2AI_item.tex seems do the right thing, but it is not shown in AI.

[LaTeX2AI_item.zip](https://github.com/isteinbrecher/latex2ai/files/10857839/LaTeX2AI_item.zip)

**Comment by isteinbrecher** [comment]
The problem is, that you are using the ghostscript version shipped with TeXLive. This version has some problems in combination with LaTeX2AI. Please install an independent version of [ghostscript](https://www.ghostscript.com/) and make sure that you set the correct path in the LaTeX2AI options. Then everything should work fine.

**Comment by wzmumu** [comment]
It works. Thanks.
