### ISSUE TITLE
Can't make a new line

### ISSUE THREAD

**Issue by tandeitnik** [isteinbrecher/latex2ai#120]
I'm trying to make a multiline text. I tried using double dash \, \newline, and shift+enter, but these commands are just ignored. Is it possible to make multiline texts with Latex2Ai?

**Comment by isteinbrecher** [comment]
Under the hood LaTeX2AI creates every item in a TikZ picture, which restricts line breaks.
There are many possible solutions for this, the first one that comes to my mind is to use a `minipage` environment:
```tex
\begin{minipage}{2cm}
First line \\
Second line
\end{minipage}
```

**Comment by tandeitnik** [comment]
It worked, thank you very much! And wow, the response was lightning fast! I really appreciate your plugin!
