### ISSUE TITLE
Somthing wrong in the path to ghostscript

### ISSUE THREAD

**Issue by C5732** [isteinbrecher/latex2ai#121]
AI2021
Here's the error msg
```
The path to the ghostscript executable
(gswin32c.exe, gswin64c.exe) seems to
be wrong. Please select the correct path
otherwise LaTeX2Al can not be used!
```
I've tried to set Environment Variables and reinstall GhostScript. But it's of no use.

**Comment by isteinbrecher** [comment]
Did you try to click OK and select the path manually? Also can you post the location of your GhostScript executables?

**Comment by C5732** [comment]
> Did you try to click OK and select the path manually? Also can you post the location of your GhostScript executables?

thx, this method works(●'◡'●)
