### ISSUE TITLE
Error in SplitPdfPages

### ISSUE THREAD

**Issue by linlinge** [isteinbrecher/latex2ai#139]
When I use latex2ai plugin in my laptop, it works well. However, I install this plugin in my desktop and modify an equation. The plugin throw an error as follows:
![image](https://github.com/isteinbrecher/latex2ai/assets/26290410/4d7dafc9-4942-4820-8bd2-7645e9fb0a08)
By a way, the version of illustrator is "Adobe illustrator 2022".

**Comment by isteinbrecher** [comment]
@linlinge thanks for reporting this issue. This seems like it could be an issue with the installation of `ghostscript`. Can you check the path to the `ghostscript`-executable listed in the LaTeX2AI options? I assume your path points to the LaTeX installation. Many LaTeX distributions come with a (old or modified) version of `ghostscript`. Unfortunately this version can not be used in combination with LaTeX2AI. If this is the case, please install the official version of `ghostscript` and set the path accordingly.

**Comment by isteinbrecher** [comment]
@linlinge is there an update on this issue? Can this be closed?

**Comment by isteinbrecher** [comment]
With the new release _v1.0.0_ the path finding mechanisms are reworked and this should not happen again, thus closing.
