### ISSUE TITLE
LaTeX2AI Error

### ISSUE THREAD

**Issue by HwT-DB** [isteinbrecher/latex2ai#141]
![image](https://github.com/isteinbrecher/latex2ai/assets/157501395/9a56bdc8-3652-4839-ac1c-c029de58dec9)

**Comment by isteinbrecher** [comment]
@HwT-DB can you state a little bit more about the error? When does it occur?

**Comment by HwT-DB** [comment]
It first occured when I wanted to save a document directly after installing LaTeX2AI. Since then it occurs with every save and every time I open AI

**Comment by isteinbrecher** [comment]
Is it possible that the document path contains non-ASCII characters? I can upload a debug version that will give more insight on where the error occurs, but I will need a couple of days to get this.

**Comment by isteinbrecher** [comment]
@HwT-DB are you using documents in the illustrator cloud? This can lead to this issue. At the moment LaTeX2AI is working in combination with documents stored locally. Also it will throw an error for cloud documents, even if the document does not contain LaTeX2AI items. This will hopefully be flexed with the next release.

**Comment by HwT-DB** [comment]
Yea, so the original document was saved in the cloud, now i have tried locally and it works without any errors!
Thank you for the help and the awesome tool
