### ISSUE TITLE
Can not found "auto_generated/version.h"

### ISSUE THREAD

**Issue by WhenMelancholy** [isteinbrecher/latex2ai#154]
Hello, I'm trying to compile this project for the 2024 version of Illustrator, but I've encountered a compilation error. It's telling me that it can't find the following header file:

```
//! Include information regarding the curent git version.
#include "auto_generated/version.h"
```

It looks like this is an automatically generated file, but my Visual Studio hasn't generated this file for me. Can I ask if you have any ideas about this?

**Comment by WhenMelancholy** [comment]
I fixed this problem by using the Python script to create the header, but I still can't use this plugin normally in the 2024 version. I get the following error when opening the AI program:

![image](https://github.com/user-attachments/assets/0e06b3fb-9932-41f0-9b3e-11bc2997f4c1)

Do you have any suggestions for fixing this? Thank you very much!

**Comment by WhenMelancholy** [comment]
OK, I fix this issue by use local document. But my illustrator interface will stuck when I try to insert math equations...

**Comment by isteinbrecher** [comment]
@WhenMelancholy nice to see that you figured out the two issues. Regarding the third one, could you explain what exactly you mean with "stuck" is the UI not loading or not responding.

Is there a specific reason you want to compile from source? There will be a new LaTeX2AI version in the very near future, that includes a lot of changes, bug fixes and also supports macOS. I suggest you try out the branch `latex2ai_for_mac`.

**Comment by isteinbrecher** [comment]
@WhenMelancholy if you still have issues, please have a look at the current `main` branch, which includes a lot of bug fixes compared to the previous state.

**Comment by WhenMelancholy** [comment]
Many thanks! I will try it

**Comment by isteinbrecher** [comment]
@WhenMelancholy could you could you resolve your issue with the current `main` (or maybe the pre-release [`v1.0.0-rc.1`](https://github.com/isteinbrecher/latex2ai/releases/tag/v1.0.0-rc.1))? Can this issue be closed?

**Comment by WhenMelancholy** [comment]
Yeah latex2ai works fine on my computer now, thank you for publish the amazing new version!
