### ISSUE TITLE
Version mismatch error

### ISSUE THREAD

**Issue by WhenMelancholy** [isteinbrecher/latex2ai#161]
![QQ_1728074408652](https://github.com/user-attachments/assets/1e2dbebe-7906-49da-ba61-f65710fa6b1b)

I kept getting this error but I already use the latest version in the release page, how can i fix this?

**Comment by isteinbrecher** [comment]
@WhenMelancholy  Thanks for reporting this. Looks like there was an issue with the version of the uploaded binaries. I updated them, could you try again with the new binaries? This should fix the error.

**Comment by isteinbrecher** [comment]
@WhenMelancholy could you resolve the error? Can this issue be closed?

**Comment by isteinbrecher** [comment]
This issue should be closed with the newly uploaded release version.
