### ISSUE TITLE
An option for the user to choose that whether "enter" or "shift+enter" should be used to produce line breaks

### ISSUE THREAD

**Issue by MGG1996** [isteinbrecher/latex2ai#168]
Hello @isteinbrecher,

I'm happy here to initiate a new request as you recommended.

Some users may be accustomed to using ”enter“ for line wrapping in other LaTeX editing environments, they are prone to triggering the compilation process incorrectly when using LaTeX2AI and needing line wrapping. Sometimes, this can lead to tedious operations.

If possible, It would be better to set a configuration option that allows users to choose whether to use ”enter“ or ”shift+enter“ for switching lines.

By the way, can the default height of the code editing area be increased? When inputting large multi line formulas, the number of lines displayed at the current height is very limited, and frequent operation of the slider is not very convenient. Perhaps this height value can also be used as an option for users to set themselves.

**Comment by isteinbrecher** [comment]
Thanks for the feature request @MGG1996 . With #180 this functionality was added to LaTeX2AI. Now enter works as expected in a standard editor, additionally SHIFT+ENTER can be used as a hotkey to close the item create / edit form. The user can select the behaviour in the settings dialog. I played around with this a little bit and it feels much more natural this way, so the new behaviour is the default. This will be in the next release.

@MGG1996 The option to change the window size is for sure a good idea, unfortunately this is not very straight forward. Could you open a separate issue on that?

**Comment by MGG1996** [comment]
OK @isteinbrecher,

As your wish, I will open a new issue for the second advice.

**Comment by isteinbrecher** [comment]
With the release of _v1.0.0_ it is now possible to select this behaviour in the options (this is actually the default now, since it feels more natural). Thanks for the suggestion @MGG1996
