### ISSUE TITLE
I tried update the version of the LaTeX2AI, but it don't works

### ISSUE THREAD

**Issue by SaprZheks** [isteinbrecher/latex2ai#171]
It spamming me
![image](https://github.com/user-attachments/assets/f0915e7b-a1e0-430f-8284-fa63d5edf2c5)
![image](https://github.com/user-attachments/assets/a44d460f-4f34-4b60-8790-273b1e896d8e)

**Comment by SaprZheks** [comment]
My Illustrator is placed in disk E

**Comment by isteinbrecher** [comment]
This looks like your Illustrator document contains non-ascii characters. This is not yet supported by LaTeX2AI. LaTeX2AI should however raise an error for such documents. Can you post the full name of your Illustrator document here?

**Comment by isteinbrecher** [comment]
With _v1.0.0_ full unicode paths are supported, thus closing.
