### ISSUE TITLE
Plugin crash in AI 2025

### ISSUE THREAD

**Issue by zhuoqun-chen** [isteinbrecher/latex2ai#173]
<img width="260" alt="image" src="https://github.com/user-attachments/assets/0b5e095e-bb5a-49ca-9638-b16696e866f8">

either custom plugin location or all-user path won't work.

I'm using Mac M1 Sequoia 15.0.1 with Adobe Illustrator 2025.

Any help would be appreciated @isteinbrecher @Nikita240 @dzhi1993

**Comment by zhuoqun-chen** [comment]
solved by trusting any software to be opened as described in https://gist.github.com/hoishing/cadd905b095e15531467255b537f6906

**Comment by isteinbrecher** [comment]
Thanks @zhuoqun-chen for reporting this. We never experienced that error. Could you post your macOS versions and if you have an intel or apple processor? Also could you post the xml file you used to solve this? Then we can add this to the installation instructions.

**Comment by zhuoqun-chen** [comment]
Hi @isteinbrecher, I'm using MacOS 15 M1 (apple processor). And here are some snippets from the original gist that I found that solved my problem:

```
Starting from macOS 15, sudo spctl --master-disable is no longer supported to disable Gatekeeper.
We need to disbale it with Configuration Profiles.
```

And the provided `sample.mobileconfig` is:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>PayloadContent</key>
    <array>
      <dict>
        <key>PayloadType</key>
        <string>com.apple.systempolicy.control</string>
        <key>PayloadUUID</key>
        <string>FIRST-UUID-HERE</string>
        <key>PayloadIdentifier</key>
        <string>com.yourcompany.profile.systempolicy</string>
        <key>PayloadDisplayName</key>
        <string>System Policy Control</string>
        <key>PayloadDescription</key>
        <string>Configures System Policy Control settings</string>
        <key>PayloadVersion</key>
        <integer>1</integer>
        <key>EnableAssessment</key>
        <false />
      </dict>
    </array>
    <key>PayloadDisplayName</key>
    <string>Disable Gatekeeper</string>
    <key>PayloadIdentifier</key>
    <string>com.yourcompany.profile</string>
    <key>PayloadRemovalDisallowed</key>
    <false />
    <key>PayloadScope</key>
    <string>System</string>
    <key>PayloadType</key>
    <string>Configuration</string>
    <key>PayloadUUID</key>
    <string>SECOND-UUID-HERE</string>
    <key>PayloadVersion</key>
    <integer>1</integer>
  </dict>
</plist>
```


I summarized how to create your own script by the provided sample.

1. use `uuidgen` create 2 uuids in terminal
2. replace `<string>FIRST-UUID-HERE</string>` with your actual first uuid in the terminal stdout
3. replace `<string>SECOND-UUID-HERE</string>` with your actual second uuid in the terminal stdout
4. double click the `.mobileconfig` file to install the profile on your Mac
5. in `system pereferences` -> `device management`, click to open the profile and enable it
6. restart the Mac

then run the script by following the original gist.

⚠️⚠️⚠️
but people needs to use this method at their own risk because in general it will allow any non-notarized apps being run without additional asking. Here is what it looks like in `Privacy & Security` section after restarting the computer:

<img width="465" alt="image" src="https://github.com/user-attachments/assets/cd8b58dc-d310-4ddb-bd1e-5a1361a573ac">

**Comment by koko35p** [comment]
You could try the "xattr" command shown in the following post to disable the gatekeeper just for a single app:[
](https://apple.stackexchange.com/questions/58509/how-can-i-open-a-single-app-by-an-unidentified-developer-without-allowing-all)

**Comment by isteinbrecher** [comment]
@koko35p did you try the approach that you posted in combination with LaTeX2AI?

**Comment by isteinbrecher** [comment]
@zhuoqun-chen thanks for posting this. Could you try if the approach posted by @koko35p also works for you? I would prefer to add instructions that do not require to completely shut down the gatekeeper.

**Comment by koko35p** [comment]
> @koko35p did you try the approach that you posted in combination with LaTeX2AI?

Yes, I used "xattr -d com.apple.quarantine (path_to_LaTeX2AI.aip)" and it works well.

**Comment by matteosecli** [comment]
I confirm that `xattr -d com.apple.quarantine (path_to_LaTeX2AI.aip)` works for me too, without any need to disable Gatekeeper. I'm on MacOS 15.1, Apple Silicon M3 Max, Illustrator 2025.

**Comment by isteinbrecher** [comment]
Thanks for the suggestion, `xattr -d com.apple.quarantine LaTeX2AI.aip` works like a charm! I will add this to the install instructions. @zhuoqun-chen is is ok if I use your image from the first post in this issue?

**Comment by zhuoqun-chen** [comment]
Hi all, I'm gonna close this since now it is now solved by @koko35p's much simpler solution. @isteinbrecher
