### ISSUE TITLE
Non-ascii filepath warning

### ISSUE THREAD

**Issue by Eltaurus-Lt** [isteinbrecher/latex2ai#177]
The plugin (v1.0.0-rc1) throws a warning popup in Illustrator CC each time a document is saved under a file path with non-ascii characters even when the document does not contain any LaTeX2AI labels.

(although after installing [the fix for CS6](https://github.com/isteinbrecher/latex2ai/issues/172#issuecomment-2453493706) I do not seem to get the warning anymore, instead an error is thrown by l2a_file_system.cpp when saving a document with an embedded label, which is puzzling since the two Illustrators (CC and CS6) and the respective plugins are installed separately )

**Comment by isteinbrecher** [comment]
Thanks for opening this issue I will have a look at this soon, should be a very similar fix as with CS6.

I am not exactly sure I fully understand the second part of your comment. Do you get the error in CS6 or CC? Could you post the error message? In general the two AI versions should not affect each other if the plug-in binaries are in saved in different directories and the respective AI versions point directly to that directory.

**Comment by Eltaurus-Lt** [comment]
> Do you get the error in CS6 or CC?

That was in CC. But that all is just a sidenote, I didn't perform thorough testing on that.

> Could you post the error message?

Not anymore, unfortunately. My trial has ended, so I reverted back to CS6. I decided to stick with that one for a while longer after all.

**Comment by isteinbrecher** [comment]
Hard to say what caused the issue. There should be no interplay between different Illustrator versions and the plugin, so let's see if this happens again for other users, then this can be tracked further. 

As for the main topic of this issue, I will try to include this into the final release version v1.0.0.

**Comment by isteinbrecher** [comment]
@Eltaurus-Lt out of interest, could you post an example file name or path that raised the warning for you?

**Comment by Eltaurus-Lt** [comment]
I'm not sure, what exactly I was editing at that time, but it must have been something inside a directory with either Cyrillic or Japanese characters in the name

**Comment by isteinbrecher** [comment]
@Eltaurus-Lt thanks, for the initial report of the issue.

With the release of _v1.0.0_ unicode paths are supported and this issue can be closed.
