### ISSUE TITLE
LaTeX2AI tool crashes Illustrator

### ISSUE THREAD

**Issue by Eltaurus-Lt** [isteinbrecher/latex2ai#189]
I might have figured the conditions which cause the crash [I've described previously](https://github.com/isteinbrecher/latex2ai/issues/172#issuecomment-2449849747). It seems to occur when I use Ctrl + left click on an empty area to deselect everything after using the tool. Switching to other tools (with either hotkeys or the tool panel) work fine, and Ctrl + left click does not cause any issues when any other tool other than LaTeX2AI is active.

Minimal steps to replicate (windows 11):
1. Create a new document and save it to a file
2. Use the LaTeX2AI tool to create new label
3. Right after the label appears (while the green outline is visible) hold Ctrl and left click anywhere

Immediately after that the Illustrator should become completely unresponsive and crash with no warnings few seconds later.

**Comment by isteinbrecher** [comment]
Thanks for this detailed error report. I can reproduce the error on Windows and macOS. It should be fixed with #190 and the new release `v1.0.2`. Can you try if this fixes the error on your machine as well?
