### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by macklinhrw** [isteinbrecher/latex2ai#80]
![image](https://user-images.githubusercontent.com/19892721/139953753-dd6e35fe-36b4-4721-9347-940e47e6f4b2.png)
I have already installed ghostscript into Program Files (x86)\gs9.55.0
(And I tried Program Files\gs\gs9.55.0)

There is no useful information on how to install ghostscript or get it working for this plugin.

**Comment by isteinbrecher** [comment]
Do you mean by >>*(And I tried Program Files\gs\gs9.55.0)*<< that you also installed the 64bit version of ghostscript? The installation path should then look like `C:\Program Files\gs\gs9.50`.

Unfortunately the automatic detection of system paths is one of the messiest things in LaTeX2AI, we are currently working on it and the behavior should be better in the upcoming releases. For now, make sure the 64bit version of ghostscript is installed in the default path and try one of the following two things:
- Remove the files under `C:\Users\USERNAME\AppData\Local\Adobe\Illustrator\LaTeX2AI\`
- Manually create the application data file `C:\Users\USERNAME\AppData\Local\Adobe\Illustrator\LaTeX2AI\LaTeX2AI_application_data.xml` with the content (replace the paths to match your system)
  ```xml
  <LaTeX2AI_options
    command_gs="GS_PATH\gswin64c.exe"
    command_latex="pdflatex"
    command_latex_options="-interaction nonstopmode -halt-on-error -file-line-error"
    path_form_exe="FORMS_PATH\LaTeX2AIForms.exe"
    path_latex=""
  />
  ```

**Comment by isteinbrecher** [comment]
@macklinhrw did you try the suggestions? Also there is a new release [`v0.0.7`](https://github.com/isteinbrecher/latex2ai/releases/tag/v0.0.7) with improved path finding, you might also want to check that one out.

If you could resolve your problem, please close this issue.
