### ISSUE TITLE
path to folder with the LaTeX executables seems to be wrong

### ISSUE THREAD

**Issue by AnselmDr** [isteinbrecher/latex2ai#90]
Hello,

the addon looks great and I'd really like to try it out. Unfortunately upon starting Illustrator, following error message is displayed:

The path to the folder with the LaTeX executables (pdflatex.exe, ...) seems to be wrong. Please select the correct path, otherwise LaTeX2AI can not be used!

When choosing the correct path (\MiKTeX\miktex\bin\x64) the same error message is being displayed again. Can you help me out? I am runnning AI CC 2018, Miktex, Win10. I tried to add the plugin to both Adobe Illustrator CC 2018\Plug-ins\LaTex2AI and Adobe Illustrator CC 2018\Support Files\Required\Plug-ins without success.

**Comment by isteinbrecher** [comment]
It seems this is a MiKTeX related issue. I uploaded a possible fix c612a4ca8ebf26b47639933e72a1112358bede38. @AnselmDr can you try if this solves your issue? Then this fix will be included in the next release.
[Uploading LaTeX2AI_c612a4ca.zip…]()

**Comment by AnselmDr** [comment]
wow, it solved the issue and the addon works. Thanks for your super fast response.
