### ISSUE TITLE
LaTeX2AI support for Adobe Illustrator 2022

### ISSUE THREAD

**Issue by F-Toe** [isteinbrecher/latex2ai#99]
LaTeX2AI.aip and LaTeX2AIForms.exe for AI 2021 do not work as a plugin in AI 2022.

**Comment by isteinbrecher** [comment]
Thanks for the feedback, it also works for me. However, there is a new SDK version for Illustrator 2022, so there will be a new release of LaTeX2AI soon, where Illustrator 2022 is officially supported.
